<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.msbuild" />
  </ItemGroup>
  
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura,json</CoverletOutputFormat>
    <CoverletOutput>./TestResults/Coverage/</CoverletOutput>
    <ExcludeByFile>**/Migrations/**/*</ExcludeByFile>
    <ExcludeByAttribute>GeneratedCodeAttribute,ExcludeFromCodeCoverageAttribute</ExcludeByAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" VersionOverride="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" VersionOverride="9.0.8" />
  <PackageReference Include="Microsoft.AspNetCore.OpenApi" VersionOverride="9.0.8" />
  <PackageReference Include="Microsoft.AspNetCore.SpaProxy" VersionOverride="9.0.8" />
  <PackageReference Include="Microsoft.EntityFrameworkCore" VersionOverride="9.0.8" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" VersionOverride="9.0.8" />
  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" VersionOverride="9.0.4" />
  <PackageReference Include="Scalar.AspNetCore" VersionOverride="1.2.76" />
    <ProjectReference Include="..\OnParDev.MyMcp.Api\OnParDev.MyMcp.Api.csproj" />
  </ItemGroup>

</Project>
