name: CI - Main Branch

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  NODE_VERSION: '18'

jobs:
  frontend-lint-test:
    name: Frontend Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OnParDev.MyMcp.Api/ClientApp
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './OnParDev.MyMcp.Api/ClientApp/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run TypeScript check
      run: npx tsc --noEmit
    
    - name: Run Vitest tests
      run: npm test

  backend-unit-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
    
    - name: Run unit tests
      run: dotnet test OnParDev.MyMcp.Api.UnitTests --no-build --configuration Release --verbosity normal --logger trx --results-directory TestResults/
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-results-main
        path: TestResults/
        retention-days: 30

  backend-integration-tests:
    name: Backend Integration Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: onpardev_mymcp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
    
    - name: Run integration tests
      run: dotnet test OnParDev.MyMcp.Api.IntegrationTests --no-build --configuration Release --verbosity normal --logger trx --results-directory TestResults/
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=onpardev_mymcp_test;Username=postgres;Password=postgres"
        CLERK__PUBLISHABLEKEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        CLERK__AUTHORITY: ${{ secrets.CLERK_AUTHORITY }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results-main
        path: TestResults/
        retention-days: 30

  backend-build:
    name: Backend Build & Analysis
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution (Release)
      run: dotnet build --no-restore --configuration Release
    
    - name: Publish API
      run: dotnet publish OnParDev.MyMcp.Api --no-build --configuration Release --output ./publish-api
    
    - name: Upload API build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: api-build-main
        path: ./publish-api/
        retention-days: 90
    
    - name: Check for build warnings
      run: dotnet build --no-restore --configuration Release --verbosity normal | tee build.log && ! grep -i "warning" build.log

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OnParDev.MyMcp.Api/ClientApp
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET (for API generation)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './OnParDev.MyMcp.Api/ClientApp/package-lock.json'
    
    - name: Install .NET dependencies
      run: dotnet restore
      working-directory: .
    
    - name: Start API for OpenAPI generation
      run: |
        dotnet build --configuration Release
        nohup dotnet run --project OnParDev.MyMcp.Api --configuration Release &
        sleep 30
      working-directory: .
      env:
        CLERK__PUBLISHABLEKEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        CLERK__AUTHORITY: ${{ secrets.CLERK_AUTHORITY }}
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Generate API client
      run: npm run generate-api
    
    - name: Build frontend
      run: npm run build
    
    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-main
        path: ./OnParDev.MyMcp.Api/ClientApp/dist/
        retention-days: 90

  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [frontend-lint-test, backend-unit-tests, backend-integration-tests, backend-build, frontend-build]
    if: always()
    
    steps:
    - name: Check all jobs status
      run: |
        echo "## CI Results for Main Branch" >> $GITHUB_STEP_SUMMARY
        echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Frontend Lint & Test | ${{ needs.frontend-lint-test.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Backend Unit Tests | ${{ needs.backend-unit-tests.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Backend Integration Tests | ${{ needs.backend-integration-tests.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Backend Build | ${{ needs.backend-build.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Frontend Build | ${{ needs.frontend-build.result }} |" >> $GITHUB_STEP_SUMMARY
        
        echo ""
        echo "Frontend Lint & Test: ${{ needs.frontend-lint-test.result }}"
        echo "Backend Unit Tests: ${{ needs.backend-unit-tests.result }}"
        echo "Backend Integration Tests: ${{ needs.backend-integration-tests.result }}"
        echo "Backend Build: ${{ needs.backend-build.result }}"
        echo "Frontend Build: ${{ needs.frontend-build.result }}"
        
        if [[ "${{ needs.frontend-lint-test.result }}" != "success" ]] || \
           [[ "${{ needs.backend-unit-tests.result }}" != "success" ]] || \
           [[ "${{ needs.backend-integration-tests.result }}" != "success" ]] || \
           [[ "${{ needs.backend-build.result }}" != "success" ]] || \
           [[ "${{ needs.frontend-build.result }}" != "success" ]]; then
          echo "❌ One or more CI checks failed"
          echo "## ❌ CI Failed" >> $GITHUB_STEP_SUMMARY
          echo "One or more checks failed. Check the individual job results above." >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "✅ All CI checks passed"
          echo "## ✅ CI Passed" >> $GITHUB_STEP_SUMMARY
          echo "All checks passed successfully. Build artifacts are ready for deployment." >> $GITHUB_STEP_SUMMARY
        fi