name: CI - Main Branch

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  NODE_VERSION: '22'

jobs:
  frontend-lint-test:
    name: Frontend Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./OnParDev.MyMcp.Api/ClientApp
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './OnParDev.MyMcp.Api/ClientApp/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run TypeScript check
      run: npx tsc --noEmit
    
    - name: Run Vitest tests with coverage
      run: npm run test:coverage

    - name: Upload frontend coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: frontend-coverage-main
        path: ./OnParDev.MyMcp.Api/ClientApp/coverage/
        retention-days: 30

  backend-unit-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
    
    - name: Run unit tests with coverage
      run: dotnet test OnParDev.MyMcp.Api.UnitTests --no-build --configuration Release --verbosity normal --logger trx --results-directory TestResults/ --collect:"XPlat Code Coverage" --settings coverlet.runsettings
    
    - name: Upload unit test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-results-main
        path: TestResults/
        retention-days: 30
        
    - name: Upload unit test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-coverage-main
        path: OnParDev.MyMcp.Api.UnitTests/TestResults/Coverage/
        retention-days: 30

  backend-integration-tests:
    name: Backend Integration Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: onpardev_mymcp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
    
    - name: Run integration tests with coverage
      run: dotnet test OnParDev.MyMcp.Api.IntegrationTests --no-build --configuration Release --verbosity normal --logger trx --results-directory TestResults/ --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=onpardev_mymcp_test;Username=postgres;Password=postgres"
        CLERK__PUBLISHABLEKEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        CLERK__AUTHORITY: ${{ secrets.CLERK_AUTHORITY }}
    
    - name: Upload integration test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results-main
        path: TestResults/
        retention-days: 30
        
    - name: Upload integration test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-coverage-main
        path: OnParDev.MyMcp.Api.IntegrationTests/TestResults/Coverage/
        retention-days: 30

  backend-build:
    name: Backend Build & Analysis
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build solution (Release)
      run: dotnet build --no-restore --configuration Release
    
    - name: Publish API
      run: dotnet publish OnParDev.MyMcp.Api --configuration Release --output ./publish-api -p:SkipFrontendBuild=true
    
    - name: Upload API build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: api-build-main
        path: ./publish-api/
        retention-days: 90

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET (for API generation)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './OnParDev.MyMcp.Api/ClientApp/package-lock.json'
    
    - name: Install .NET dependencies
      run: dotnet restore
    
    - name: Start API for OpenAPI generation
      run: |
        dotnet build --configuration Release
        nohup dotnet run --project OnParDev.MyMcp.Api --configuration Release &
        sleep 30
      env:
        CLERK__PUBLISHABLEKEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        CLERK__AUTHORITY: ${{ secrets.CLERK_AUTHORITY }}
    
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./OnParDev.MyMcp.Api/ClientApp
    
    - name: Generate API client
      run: npm run generate-api
      working-directory: ./OnParDev.MyMcp.Api/ClientApp
    
    - name: Build frontend
      run: npm run build
      working-directory: ./OnParDev.MyMcp.Api/ClientApp
    
    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-main
        path: ./OnParDev.MyMcp.Api/ClientApp/dist/
        retention-days: 90

  coverage-summary:
    name: Coverage Summary
    runs-on: ubuntu-latest
    needs: [frontend-lint-test, backend-unit-tests, backend-integration-tests]
    if: always() && (needs.frontend-lint-test.result == 'success' || needs.backend-unit-tests.result == 'success' || needs.backend-integration-tests.result == 'success')

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    
    - name: Download all coverage artifacts
      uses: actions/download-artifact@v4
      with:
        path: coverage-artifacts/
    
    - name: Generate merged coverage report
      run: |
        mkdir -p merged-coverage
        reportgenerator \
          -reports:"coverage-artifacts/unit-test-coverage-main/**/*.cobertura.xml;coverage-artifacts/integration-test-coverage-main/**/*.cobertura.xml" \
          -targetdir:"merged-coverage" \
          -reporttypes:"Html;JsonSummary;Badges" \
          -assemblyfilters:"-OnParDev.MyMcp.Api.UnitTests;-OnParDev.MyMcp.Api.IntegrationTests" \
          || echo "No backend coverage found"
    
    - name: Upload merged coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-main
        path: merged-coverage/
        retention-days: 90
    
    - name: Print coverage summary
      run: |
        echo "## 📊 Coverage Summary" >> $GITHUB_STEP_SUMMARY
        
        # Backend coverage
        if [ -f "merged-coverage/Summary.json" ]; then
          backend_coverage=$(cat merged-coverage/Summary.json | jq -r '.summary.linecoverage // 0')
          echo "**Backend Coverage**: ${backend_coverage}%" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Frontend coverage
        if [ -f "coverage-artifacts/frontend-coverage-main/coverage-summary.json" ]; then
          frontend_coverage=$(cat coverage-artifacts/frontend-coverage-main/coverage-summary.json | jq -r '.total.lines.pct // 0')
          echo "**Frontend Coverage**: ${frontend_coverage}%" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "Coverage reports stored as build artifacts." >> $GITHUB_STEP_SUMMARY

